#!/bin/bash
# Criterion 2: a ServiceMonitor picks up the application without editing
# Prometheus configuration - which also completes criterion 1's "and your
# application".
#
# The check is that the target is UP in Prometheus, not that a ServiceMonitor
# object exists. An object that matches nothing is the failure this step is
# about, and it is indistinguishable from a working one by `kubectl get`.
NS=monitoring
PROM="http://kps-kube-prometheus-stack-prometheus:9090"

q() {
  kubectl run vq$RANDOM --rm -i --restart=Never --image=curlimages/curl:8.10.1 -n "$NS" \
    --command -- curl -s --max-time 20 "$PROM/api/v1/$1" 2>/dev/null \
    | sed 's/}{"status"/}\n{"status"/g' | head -1
  # The sed is not cosmetic. `kubectl run -i` emits the Pod's stdout twice,
  # concatenated on one line as ...}}{"status":..., so a plain head -1 keeps
  # both. Every numeric extraction then saw "14\n14", failed the digits-only
  # guard, and silently read as 0 - a verifier reporting "0 targets are up"
  # about a cluster scraping fourteen of them.
}

# The numeric value of the first result, or empty. Kept in one place because
# every ad-hoc variant of this got the quoting or the anchoring subtly wrong.
val() {
  echo "$1" | grep -o '"value":\[[^]]*\]' | head -1 | sed 's/.*,"//; s/"\]*$//'
}
int() { v=$(val "$1"); v=${v%%.*}; case "$v" in ''|*[!0-9]*) echo 0 ;; *) echo "$v" ;; esac; }

kubectl get servicemonitor web -n shop >/dev/null 2>&1 || {
  echo "FAIL: no ServiceMonitor named web in the shop namespace"; exit 1; }

# Give the operator time to reload after a late edit; the reconcile is not
# instant and a learner clicking straight through would otherwise be told
# their correct answer is wrong.
for i in $(seq 1 18); do
  RES=$(q "query?query=up%7Bnamespace%3D%22shop%22%7D")
  echo "$RES" | grep -q '"value"' && break
  sleep 10
done

if ! echo "$RES" | grep -q '"value"'; then
  echo "FAIL: Prometheus has no up{namespace=\"shop\"} target"
  echo ""
  echo "      The ServiceMonitor exists, so it is matching nothing. Two"
  echo "      reasons, both silent, and it is usually both:"
  echo ""
  echo "      1. Prometheus only selects ServiceMonitors matching its"
  echo "         serviceMonitorSelector - here release=kps. Check:"
  echo "           kubectl get servicemonitor web -n shop --show-labels"
  echo "      2. endpoints[].port is a Service port NAME, not a number. A"
  echo "         Service made by 'kubectl expose' has an unnamed port. Check:"
  echo "           kubectl get svc web -n shop -o jsonpath='{.spec.ports[0].name}'"
  exit 1
fi

# Both application Pods, not just one: a selector that matches a single Pod by
# accident would satisfy a laxer check while proving nothing about discovery.
COUNT=$(int "$(q 'query?query=count(up%7Bnamespace%3D%22shop%22%7D%3D%3D1)')")
if [ "$COUNT" -lt 2 ]; then
  echo "FAIL: only $COUNT application target(s) are up; expected one per Pod"
  echo "      The Service selector is matching fewer Pods than are running."
  exit 1
fi

# Freshness, not just presence.
#
# An instant query returns the most recent sample within Prometheus's lookback
# window - five minutes by default - so `up` keeps answering for minutes after
# scraping has stopped entirely. Removing the release label and re-running this
# check passed, because the corpse was still warm. Assert the newest sample is
# recent enough to mean "being scraped now" at a 15s interval.
STALE=$(int "$(q 'query?query=max(time()%20-%20timestamp(up%7Bnamespace%3D%22shop%22%7D))')")
if [ "$STALE" -gt 90 ]; then
  echo "FAIL: the newest application sample is ${STALE}s old"
  echo "      The target was being scraped and has stopped, so Prometheus is"
  echo "      still serving the last value it saw. Check the ServiceMonitor"
  echo "      still carries release=kps and still names a real Service port."
  exit 1
fi

# The application's own metric must be arriving, not just the synthetic `up`.
# `up` is generated by Prometheus for any endpoint it can reach, so a Service
# pointing at the wrong thing still reports up=1. `version` is chosen over
# http_requests_total because this app only exports the latter once it has
# served a request, which would make the check depend on traffic.
APP=$(q "query?query=version%7Bjob%3D%22web%22%7D")
echo "$APP" | grep -q '"value"' || {
  echo "FAIL: the target is up but exports none of the application's metrics"
  echo "      Prometheus is reaching something, but not the application's"
  echo "      /metrics endpoint - check the port and targetPort."
  exit 1; }

echo "PASS - $COUNT application targets discovered by ServiceMonitor, exporting their own metrics"
exit 0
