#!/bin/bash
# Criterion 2: the password was generated by Terraform and appears in no file
# you wrote.
#
# Both halves are checked, and the second one is checked against the *.tf files
# specifically - because the password IS in terraform.tfstate, and a check that
# searched the whole directory would fail a correct answer. That distinction is
# the point of the step.
A="aws --endpoint-url=http://localhost:4566"
IAC=/root/iac

command -v aws >/dev/null 2>&1 || { echo "FAIL: the AWS CLI is not installed"; exit 1; }
for i in $(seq 1 20); do
  curl -s --max-time 5 http://localhost:4566/_localstack/health 2>/dev/null | grep -q secretsmanager && break
  sleep 3
done

SECRET=$($A secretsmanager get-secret-value --secret-id platform/db/credentials \
  --query SecretString --output text 2>/dev/null)
[ -n "$SECRET" ] || {
  echo "FAIL: no secret at platform/db/credentials"
  echo "      Run terraform apply in $IAC."
  exit 1; }

PW=$(echo "$SECRET" | jq -r .password 2>/dev/null)
[ -n "$PW" ] && [ "$PW" != "null" ] || { echo "FAIL: the secret has no password field"; exit 1; }

# Generated, not typed. A 24-character random string is not something a person
# chose, and a short or obvious one means the resource was bypassed.
if [ "${#PW}" -lt 16 ]; then
  echo "FAIL: the password is ${#PW} characters"
  echo "      random_password with length = 24 produces something no human"
  echo "      picked. A short value means it was typed in somewhere."
  exit 1
fi
case "$PW" in
  *password*|*changeme*|*admin*|*secret123*)
    echo "FAIL: the password looks chosen rather than generated"; exit 1 ;;
esac

# It has to be Terraform's doing, not a hand-run CLI call.
[ -f "$IAC/terraform.tfstate" ] || {
  echo "FAIL: no terraform.tfstate in $IAC - this was not applied by Terraform"; exit 1; }
grep -q 'random_password' "$IAC/terraform.tfstate" || {
  echo "FAIL: no random_password resource in state"
  echo "      The secret exists but Terraform did not generate its password."
  exit 1; }
# Read the attribute with jq rather than grepping for the value.
#
# State is JSON and JSON escapes characters: a & in the password is stored as
# \u0026, so a literal grep for the password finds nothing in a file that
# plainly contains it. The first version of this check did exactly that and
# would have failed a correct answer - and, worse, is the same mistake that
# makes someone conclude their state file holds no secrets.
STATE_PW=$(jq -r '.resources[]? | select(.type=="random_password") | .instances[0].attributes.result' \
  "$IAC/terraform.tfstate" 2>/dev/null | head -1)
[ "$STATE_PW" = "$PW" ] || {
  echo "FAIL: the password in Secrets Manager is not the one Terraform generated"
  echo "      Something overwrote the secret outside Terraform."
  exit 1; }

# And absent from the configuration - the .tf files, which are what "a file you
# wrote" means. State is deliberately excluded: it contains the password by
# design, and step 1 is about knowing that.
if grep -rq -F -- "$PW" "$IAC"/*.tf 2>/dev/null; then
  echo "FAIL: the password appears in a .tf file"
  grep -rn -F -- "$PW" "$IAC"/*.tf 2>/dev/null | head -2
  echo "      Generate it with random_password and reference the attribute;"
  echo "      never paste the value back into the configuration."
  exit 1
fi

# The endpoint belongs with the password, or the application still needs its
# own configuration and step 3 cannot work.
for F in username host port dbname; do
  V=$(echo "$SECRET" | jq -r ".$F" 2>/dev/null)
  [ -n "$V" ] && [ "$V" != "null" ] || {
    echo "FAIL: the secret has no $F"
    echo "      Store the endpoint alongside the password - an application that"
    echo "      reads one secret and gets everything it needs to connect has no"
    echo "      host name in its configuration to go stale."
    exit 1; }
done

echo "PASS - a ${#PW}-character Terraform-generated password is in Secrets Manager, in no .tf file, with its endpoint"
exit 0
